### ISSUE TITLE
Builds aren't working on OS X.

### ISSUE THREAD

**Issue by rgbkrk** [nteract/zmq-prebuilt#1]
In reality, I only need to do this per tagged release which I can do in automation for Windows and Linux in the :cloud: while doing the Mac builds on my local box.

**Comment by minrk** [comment]
Does prebuild do any bundling/static linking of libs? If not, you are going to need to use something like [delocate](https://github.com/matthew-brett/delocate) to grab libzmq and pull it into the distributed files.

Bonus points: If prebuild did delocate's task automagically, that would be super.

**Comment by rgbkrk** [comment]
> Does prebuild do any bundling/static linking of libs?

You know... I have no idea. I'll go ahead and ask in https://github.com/mafintosh/prebuild/issues/81

**Comment by minrk** [comment]
Closing because Travis OS X builds are passing.
