### ISSUE TITLE
End to End Next Steps

### ISSUE THREAD

**Issue by rgbkrk** [nteract/zmq-prebuilt#20]
Woo! We've got the OS X builds working with a builtin libzmq, full end-to-end working with nteract. Next steps:

* [x] Get it working for Linux
* [x] Windows
* [ ] Make PRs to adapt that prebuild work to the "official" https://github.com/JustinTulloss/zeromq.node

**Comment by captainsafia** [comment]
Ditto that! I should be able to get Linux stuff working by 8/15.

**Comment by rgbkrk** [comment]
Sounds like a great target date. Thanks @captainsafia!

**Comment by rgbkrk** [comment]
Since @lgeiger has been making those PRs and we keep intending to, I'll close this generic issue since we're in a good place.
