### ISSUE TITLE
Fix the monitor (or test)

### ISSUE THREAD

**Issue by rgbkrk** [nteract/zmq-prebuilt#28]
Right now the monitor test is timing out:

```
  socket.monitor
    ◦ should be able to monitor the socket:
```

Which makes our tests fail. Would love help @minrk.

**Comment by minrk** [comment]
I'll try to figure out what's up. I have a vague recollection that this may have been one of the things I fixed here after forking, and I may have un-fixed it when I pulled again from upstream trying to fix the Windows builds.
