### ISSUE TITLE
Deploy prebuilds with travis and appveyor

### ISSUE THREAD

**Issue by lgeiger** [nteract/zmq-prebuilt#34]
We could use travis to automatically deploy the prebuilds to github if a new tag is pushed. This would make shipping new versions a lot easier.

If this is something you like to see, I'm happy to fiddle around with travis and make a PR.

---
Edit:
- [x] travis
- [ ] appveyor

**Comment by captainsafia** [comment]
Sure! We talked about this earlier but there was a blocker on it. Feel free to take a stab at it if you have time.

**Comment by rgbkrk** [comment]
Yup! [Big](https://github.com/getcarina/carina/blob/master/Makefile#L49) [fan](https://github.com/getcarina/dvm/blob/master/Makefile#L27) of [building on tags](https://github.com/rackspace/rack/blob/master/script/prep-travis-release.sh#L99-L104).
