### ISSUE TITLE
Release Steps

### ISSUE THREAD

**Issue by rgbkrk** [nteract/zmq-prebuilt#38]
Now that we have prebuilds for all OSes that trigger on tags thanks to:

* @captainsafia 
* @lgeiger 
* @minrk 

It's time to figure out how to do releases.

I just realized that when making a release we'll want to do:

```
npm version minor && git push && git push --tags
```

Followed by waiting for the prebuilds to come back for each OS, then finally running:

```
npm publish
```

**Comment by rgbkrk** [comment]
I'm letting 1.3.0 run the course now:

* [v1.3.0 on Travis CI](https://travis-ci.org/nteract/zmq-prebuilt/builds/159034267)
* [v1.3.0 on Appveyor](https://ci.appveyor.com/project/rgbkrk/zmq-prebuilt/build/1.0.119)

**Comment by rgbkrk** [comment]
Looks like the credentials for Windows are not good:

```
prebuild info build Packing build\Release\zmq.node into prebuilds\zmq-prebuilt-v1.3.0-node-v48-win32-x64.tar.gz
prebuild info build Prebuild written to prebuilds\zmq-prebuilt-v1.3.0-node-v48-win32-x64.tar.gz
prebuild info build Uploading 5 prebuilds(s) to Github releases
prebuild ERR! build Error: Error from GitHub: Bad credentials
```

**Comment by rgbkrk** [comment]
(note that I haven't run `npm publish` yet, will do once we've uploaded for Windows)

**Comment by rgbkrk** [comment]
Ok, we shipped our first all OSes release!

![screen shot 2016-09-10 at 4 01 10 pm](https://cloud.githubusercontent.com/assets/836375/18414016/06027e18-7770-11e6-98a6-60c842cd2cc2.png)

**Comment by rgbkrk** [comment]
Now shipping a patch release since we think we've worked out the kinks.

**Comment by rgbkrk** [comment]
Woo! We just did end to end with no fuss using:

```
npm version patch && git push && git push --tags
```

Amusingly, since @lgeiger used his key on Travis he makes every release. ;) Hand crafted.

**Comment by rgbkrk** [comment]
I had suspicion that this wasn't really working since the Windows builds were 1/3 the size of the others. Turns out, that's correct. We don't have Windows here yet. We do have a streamlined build and release process though!

**Comment by lgeiger** [comment]
> I had suspicion that this wasn't really working since the Windows builds were 1/3 the size of the others.

This is not an appveyor problem. I can reproduce this on a local 64 bit installation with visual studio 2015 as well (`git lfs` has to be installed as well, otherwise there are some strange linker errors).
