### ISSUE TITLE
Fallback to building on user's machine if prebuild unavailable

### ISSUE THREAD

**Issue by captainsafia** [nteract/zmq-prebuilt#41]
@n-riesco mentioned that we should fallback to building libzmq on the user's machine if they don't have a prebuild for their machine.

**Comment by rgbkrk** [comment]
The old behavior was:

* Build using their system libzmq, assuming they have it installed

If we end up building libzmq for them too, I think that's ok.

**Comment by lgeiger** [comment]
Is there a way we can test if the fallback is working? (I'm happy to do this next week)

The only option that comes to my mind would be to do some kind of prerelease without uploading binaries and then trying to install it.

**Comment by lgeiger** [comment]
One other question comes to my mind:

What happens if we use `zmq-prebuilt` inside an Atom package and the user updates Atom (so the shipped node version changes). Would `prebuild` download the new binary on `apm rebuild`?

**Comment by rgbkrk** [comment]
> What happens if we use zmq-prebuilt inside an Atom package and the user updates Atom (so the shipped node version changes). Would prebuild download the new binary on apm rebuild?

Good point. If it doesn't, we should make sure it does.

**Comment by rgbkrk** [comment]
> Is there a way we can test if the fallback is working? 

One way would be to create a project and point the entry in the `package.json` to your local git repo instead of the package on npm.

**Comment by lgeiger** [comment]
> One way would be to create a project and point the entry in the package.json to your local git repo instead of the package on npm.

You mean via `npm link`?

**Comment by lgeiger** [comment]
The fallback on windows works! I've tested it with `v1.2.0` where no windows binaries are available. 

Actually that's not that surprising since we didn't change the windows section of the gyp file.
If we remove the windows binaries from the new releases and tell people to install visual studio or the [c++ compiler tools](http://landinghub.visualstudio.com/visual-cpp-build-tools). We could make nteract on windows work again.

**Comment by rgbkrk** [comment]
Awesome! We need to make sure the fallback works on Linux and OS X next.

**Comment by lgeiger** [comment]
Closed by #52
