### ISSUE TITLE
Only compiles with Visual Studio 2015

### ISSUE THREAD

**Issue by lgeiger** [nteract/zmq-prebuilt#53]
`zmq-prebuilt` only compiles with Visual Studio ~~2013~~2015. [This line](https://github.com/nteract/zmq-prebuilt/blob/master/binding.gyp#L11) makes sure that gyp uses  Visual Studio ~~2013~~2015.

If it this line is removed gyp tries to build with the systems default compiler and will fail: https://ci.appveyor.com/project/lgeiger/zmq-prebuilt/build/1.0.96/job/fy8vt6rql9hqsade#L60

This is probably because the included libs are built with Visual Studio 2013. Is there something we can do about that?

**Comment by lgeiger** [comment]
Maybe relevant as an alternative solution:
- https://github.com/zeromq/libzmq/tree/master/builds/msvc
- https://github.com/zeromq/libzmq/blob/master/builds/gyp/project.gyp

**Comment by rgbkrk** [comment]
If we take a hard stance on only support ZeroMQ 4.1.5+, I think we can make it so that we don't _have_ to use Visual Studio 2013.

**Comment by lgeiger** [comment]
@rgbkrk ZeroMQ 4.2.0 will provide build targets for VS 2008-2015 then we can aim for building ZeroMQ from source as we do on unix.

Till then I try to build a static lib with VS 2015 so we can recommend [`windows-build-tools`](https://github.com/felixrieseberg/windows-build-tools).

**Comment by lgeiger** [comment]
We have the builds working very well with VS 2015 now.
@rgbkrk Do you think this issue has high priority? I fear it could introduce strange bugs into our current setup. Otherwise I'd close it.

**Comment by rgbkrk** [comment]
I'm happy with it working with only VS 2015, this plugs in really well with `windows-build-tools`.

We can close this.
