### ISSUE TITLE
Remove ZMQ version related code

### ISSUE THREAD

**Issue by lgeiger** [nteract/zmq-prebuilt#67]
I noticed quite a bit of code for handling old ZMQ versions. Since we bundle ZMQ 4.1.5 we could remove it.
Should we do this?

**Comment by rgbkrk** [comment]
I'm certainly a fan. What happens when we want to support the coming 4.2 release?

I'd be curious to hear @minrk's thoughts.

**Comment by minrk** [comment]
If you always bundle or build libzmq, there's no need to keep that stuff. You will want to keep something like that if you want to support linking libzmq installed on the system. This can be a useful fallback so you don't have to ensure that your scripts build libzmq on every platform. It comes up at pyzmq for things like AIX, Solaris, POWER, where the bundled libzmq isn't helpful.

There's very little to do to support most of 4.2. It's mainly a few extra socket types, and some implementations of poller functionality that isn't particularly relevant for higher level bindings.

**Comment by lgeiger** [comment]
Closed by #76
