### ISSUE TITLE
Make the Windows libs be an optional dependency

### ISSUE THREAD

**Issue by rgbkrk** [nteract/zmq-prebuilt#70]
We could make a separate package that is just the libs we bundle for Windows, using [optional dependencies](https://docs.npmjs.com/files/package.json#optionaldependencies) - it would "fail" on non-Windows systems (so no local artifact) and succeed on Windows. Our gyp config then has to refer to the lib asset within this other package.

**Comment by lgeiger** [comment]
I like that idea! Would it work for different architectures as well or would it download both 32 and 64-bit libraries?

Since we have a nice download script (node) we could also host them somewhere (maybe a github release) and download the right version like we do with the ØMQ source on unix.

**Comment by rgbkrk** [comment]
Ah yeah then we don't even need a separate package necessarily - it can fetch the asset directly.

I'm imagining we can make separate versions for 32-bit and 64-bit.
